# Theoretical Questions

**Question 1: Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

**ANS 1]** Numpy stands for Numerical Python. It is one of the most widely used libraries in Python for scientific computing and data analysis. Numpy is a tool that helps us work with lots of numbers with a very high speed.

Advantages of Numpy:

Faster Calculations: Doing Math with lists in Python takes a lot of time if there is lot of data. But since Numpy is implemented using C language which is one of the fastest programming language, all the mathematical calculations are performed at high speed.

More Control: With Numpy we can do slicing of data, and we can also reshaoe the data without any hassle.

Availability of better Math Tools: Numpy gives us Various tools for working with numbers. If we want to do things like multiply matrices, find averages, or do more complex math, Numpy makes it easy.

The above mentioned features of Numpy make Python better for maths.

**Question 2: Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

**ANS 2]** Both np.mean() and np.average() are functions in Numpy that help you calculate the average of numbers.

np.mean() always calculates a simple average

np.average() can also calculate the simple average but can be customized with weights to give different importance to each number.

When you need average of all numbers equally use np.mean() but when you need to consider some numbers more important than others, you need to use weights. In this case np.average()


**Question 3: Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

**ANS 3]** Reversing 1D Array:

A 1D array is like a list of numbers, and to reverse it, you just flip the order of the numbers.
You can use slicing to reverse a 1D array.
The syntax for slicing is array[start:stop:step], and to reverse, we set the step as -1.

Reversing 2D Array:

2D Array can be reversed in 2 ways: 1] Reversing along rows
2] Reversing along columns

1] Reversing along rows:

To flip array upside down we can use sicing along axis 0

2] Reversing along Columns:

If you want to reverse order of number along each row, we need to reverse along axis 1


Reversing 2D Array along both the axes:

To reverse an Array along both rows and columns you can use array_name[::-1, ::-1]


In [2]:
#Reversing 1D Array
import numpy as np
arr = np.array([1,2,5,6,9])
print("Original 1D Array: ",arr)
print("Reversed 1D Array: ",arr[::-1])

#Reversing 2D Array along rows
arr1 = np.array([[1,2,3],[11,22,33],[111,222,333]])
print("Original 2D Array: \n",arr1)
print("Reversed 2D Array along rows: \n",arr1[::-1,:])

#Reversing 2D Array along columns
print("Reversed 2D Array along columns: \n",arr1[:,::-1])

#Reversing 2D Array along both axes
print("Reversing 2D array along both the axes: \n",arr1[::-1,::-1])


Original 1D Array:  [1 2 5 6 9]
Reversed 1D Array:  [9 6 5 2 1]
Original 2D Array: 
 [[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
Reversed 2D Array along rows: 
 [[111 222 333]
 [ 11  22  33]
 [  1   2   3]]
Reversed 2D Array along columns: 
 [[  3   2   1]
 [ 33  22  11]
 [333 222 111]]
Reversing 2D array along both the axes: 
 [[333 222 111]
 [ 33  22  11]
 [  3   2   1]]


**Question 4: How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**

**ANS 4]** In Numpy we can find Datatype of elements by using dtype attribute. This tell us datatype of data that is stored in array.

Importance of datatypes in memory management:

Different datatypes take up different amount of memory allocated to them. If you dont specify right datatype, Numpy may use more memory than necessary and this can lead to memory wastage.

Smaller datatypes are faster. When you use smaller datatypes computer can process data faster because it doesnt have to deal with large amounts of data.

**Question 5: Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**ANS 5]** ndarrays in Python:

ndarray is main object for numpy and it stands for N-dimensional array. It is special type of array used to store large amount of data in a way that makes working with that data more easier and efficient.

Key Features of ndarray:

1] Homogenous: All elements of ndarray must be of same datatype.
2] Fixed size: Once you create ndarray, its size cannot be changed
3] Fast and efficient: ndarrays use less memory and are faster to work with than python lists.
4] Multiple Dimensions: ndarray have multiple dimensions like 1D, 2D, 3D etc which makes it easy to represent data like vectors or matrices or any other higher dimensional data.

ndarrays differ from python list in:

1] Speed and performance: ndarrays are faster and more efficient than python list.
2] Homogeneity: In python list we can store elements of different datatypes but in ndarray all elemnts should be of same datatype.
3] Operations: With python list we have to use loops to do operations like addition, multiplication on entire list but with ndarray we can do these directly on entire array which is musch faster and easier.

**Question 6: Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

**ANS 6]** Speed:
Numpy arrays are faster than Python lists when doing math with numbers. This is because Numpy is built in a way that's super quick for calculations, while Python lists are slower because they are more general and can hold different types of data.

Memory Efficiency:
Numpy arrays use less memory than Python lists. In Numpy, all elements are stored together in a more compact way, while python lists store extra information that takes up more space.

No Loops Needed:
With Numpy, you can do math on the whole array without needing loops, which makes it faster. In python lists, you need loops to do the same thing, which slows everything down.

Handling Large Data:
Numpy is better for working with big datasets. It can handle large arrays or matrices of numbers quickly and with less memory.

**Question 7: Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

**ANS 7]** vstack() and hstack() are functions in numpy that stack two arrays together but in different ways.

hstack(): This function stacks array horizontally i.e side by side, it combines arrays along the columns.

vstack(): This function stacks array vertically i.e on top of each other, it combines array along the rows.

In [ ]:
#Example of using hstack() and vstack()

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Printing Example of hstack(): \n",np.hstack((arr1,arr2)))
print("Printing Example of vstack(): \n",np.vstack((arr1,arr2)))

Printing Example of hstack(): 
 [1 2 3 4 5 6]
Printing Example of vstack(): 
 [[1 2 3]
 [4 5 6]]


**Question 8: Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

**ANS 8]** fliplr() and flipud() are functions that are used to flip arrays in different ways.

fliplr(): This function is flip left to right function. It flips array horizontally i.e from left to right.

flipud(): This function id flip up to down function. It flips array vertically i.e from up to down.

Effects of these functions on various array dimensions.

Effects on 2D arrays: fliplr() on 2D arrays will flip each row horizontally and flipud() on 2D arrays will flip entire array vertically.

Effects on 1D arrays: fliplr() on 1D array will flip the array horizontally  but flipud() will not havea any effect on array. Since, array is one dimensional and it does not have many rows to flip with.

In [ ]:
#Examples of using fliplr() and flipud() on 2D and 1D arrays
arr = np.array([[1,2,3],[4,5,6]])
print("Original 2D array: \n",arr)
print("2D Array after using fliplr(): \n", np.fliplr(arr))
print("2D Array after using flipud(): \n", np.flipud(arr))

arr1 = np.array([1,2,3])
print("\nOriginal 1D Array: \n",arr1)
#print("1D Array after using fliplr(): \n", np.fliplr(arr1)) Gives error because it expects 2D array as an input
print("1D Array after using flipud(): \n", np.flipud(arr1))

Original 2D array: 
 [[1 2 3]
 [4 5 6]]
2D Array after using fliplr(): 
 [[3 2 1]
 [6 5 4]]
2D Array after using flipud(): 
 [[4 5 6]
 [1 2 3]]

Original 1D Array: 
 [1 2 3]
1D Array after using flipud(): 
 [3 2 1]


**Question 9: Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

**ANS 9]** The array_split() method of numpy is used to split the array into smaller arrays. We can specify in how many parts we wish to split the array.

Syntax: np.array_split(array, indices/Sections)
array: The array that we want to split
indices/Sections: List of indices where we want to split the array/ Number of sections into which we wish to split the array.

If the number of elements in the array is not evenly divisible by the number of parts, Numpy will try to balance it as evenly as possible by giving the extra elements to the first parts.

In [ ]:
#Uneven splitting of elements
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Original array: ",arr)
print("Array splitted into 4 parts: ",np.array_split(arr,4)) #Will add extra element to the first group

Original array:  [1 2 3 4 5 6 7 8 9]
Array splitted into 4 parts:  [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


**Question 10: Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

**ANS 10]** Vectorization and broadcasting are techniques that make working with arrays faster and easier. They allow you to perform complex operations on large arrays without writing loops, which makes your code more efficient.

Vectorization: Vectorization in numpy means using special methods to do many operations at once. Suppose you have a list and you wish to add a number to each value in list, Instead of using for loop to do this step repeatedly vectorization lets you do thi one step

Broadcasting: Broadcasting is a way of making Numpy arrays with different shapes work together without needing to change their sizes. When you perform operations on arrays, Numpy automatically "stretches" smaller arrays to match the size of the bigger ones, so they can be combined easily.

In [4]:
#Example of vectorization:
arr = np.array([1,2,3,4,5])
print("Original array: ",arr)
print("Array after vectorization: ",arr+10)

Original array:  [1 2 3 4 5]
Array after vectorization:  [11 12 13 14 15]


# Practical Questions:

**Question 1: Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

**ANS 1]**

In [6]:
arr = np.random.randint(1,101,(3,3))
print("Original Array: \n",arr)
arr = arr.T
print("Array after interchanging rows and columns: \n",arr)

Original Array: 
 [[36 29 94]
 [60 85 59]
 [84 91 54]]
Array after interchanging rows and columns: 
 [[36 60 84]
 [29 85 91]
 [94 59 54]]


**Question 2: Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

**ANS 2]**

In [9]:
arr = np.array([11,22,33,44,55,66,77,88,99,00])
print("Original array: \n",arr)
print("2 x 5 array: \n", arr.reshape(2,5))
print("5 x 2 array: \n", arr.reshape(5,2))

Original array: 
 [11 22 33 44 55 66 77 88 99  0]
2 x 5 array: 
 [[11 22 33 44 55]
 [66 77 88 99  0]]
5 x 2 array: 
 [[11 22]
 [33 44]
 [55 66]
 [77 88]
 [99  0]]


**Question 3: Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

**ANS 3]**

In [14]:
arr = np.random.random((4, 4))
print("Original array: \n",arr)
print("Array with padding: \n", np.pad(arr,pad_width=1, mode="constant", constant_values = 0))


Original array: 
 [[0.89004113 0.34634846 0.39128177 0.27099499]
 [0.07662638 0.13734372 0.10838191 0.02807213]
 [0.23230971 0.48001702 0.12117534 0.88792559]
 [0.11676823 0.58919643 0.45394233 0.47072467]]
Array with padding: 
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.89004113 0.34634846 0.39128177 0.27099499 0.        ]
 [0.         0.07662638 0.13734372 0.10838191 0.02807213 0.        ]
 [0.         0.23230971 0.48001702 0.12117534 0.88792559 0.        ]
 [0.         0.11676823 0.58919643 0.45394233 0.47072467 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**Question 4: Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

**ANS 4]**

In [15]:
arr = np.arange(10,61,5)
print("Array of integers from 10 to 60 with a step of 5: \n",arr)

Array of integers from 10 to 60 with a step of 5: 
 [10 15 20 25 30 35 40 45 50 55 60]


**Question 5: Create a NumPy array of strings ['python', 'numpy','pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**

**ANS 5]**

In [16]:
arr = np.array(['python', 'numpy','pandas'])
print("Original array: ",arr)
print("Uppercase array: ",np.char.upper(arr))
print("Lowercase array: ",np.char.lower(arr))
print("Titlecase array: ",np.char.title(arr))
print("Capitalize array: ",np.char.capitalize(arr))

Original array:  ['python' 'numpy' 'pandas']
Uppercase array:  ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array:  ['python' 'numpy' 'pandas']
Titlecase array:  ['Python' 'Numpy' 'Pandas']
Capitalize array:  ['Python' 'Numpy' 'Pandas']


**Question 6: Generate a NumPy array of words. Insert a space between each character of every word in the array**

**ANS 6]**

In [17]:
arr = np.array(['Hello','World','Lets','Learn','Python'])
print("Original array: ",arr)
print("Array after inserting space between each character of every word: ",np.char.join(" ",arr))

Original array:  ['Hello' 'World' 'Lets' 'Learn' 'Python']
Array after inserting space between each character of every word:  ['H e l l o' 'W o r l d' 'L e t s' 'L e a r n' 'P y t h o n']


**Question 7: Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division**

**ANS 7]**

In [21]:
arr1 = np.array([[11,22,33],[44,55,66],[77,88,99]])
arr2 = np.array([[99,88,77],[66,55,44],[33,22,11]])
print("Array 1: \n",arr1)
print("Array 2: \n",arr2)
add_result = arr1+arr2
print("Addition of both arrays: \n",add_result)
sub_result = arr1-arr2
print("Subtraction of both arrays: \n",sub_result)
mul_result = arr1*arr2
print("Multiplication of both arrays: \n",mul_result)
div_result = arr1/arr2
print("Division of both arrays: \n",div_result)

Array 1: 
 [[11 22 33]
 [44 55 66]
 [77 88 99]]
Array 2: 
 [[99 88 77]
 [66 55 44]
 [33 22 11]]
Addition of both arrays: 
 [[110 110 110]
 [110 110 110]
 [110 110 110]]
Subtraction of both arrays: 
 [[-88 -66 -44]
 [-22   0  22]
 [ 44  66  88]]
Multiplication of both arrays: 
 [[1089 1936 2541]
 [2904 3025 2904]
 [2541 1936 1089]]
Division of both arrays: 
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


**Question 8: Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements**

**ANS 8]**

In [22]:
identity_matrix = np.identity(5)
print("Identity matrix: \n",identity_matrix)
print("Diagonal elements of identity matrix: ",np.diag(identity_matrix))

Identity matrix: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements of identity matrix:  [1. 1. 1. 1. 1.]


**Question 9: Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**

**ANS 9]**

In [23]:
def isPrime(n):
    if n==1 or n==0:
        return False
    for i in range(2,n):
        if n%i==0:
            return False
    return True


arr = np.random.randint(0,1001,100)
print("Original array: ",arr)
print("Prime numbers in array: ",arr[np.vectorize(isPrime)(arr)])

Original array:  [590 523 279 856 327 949 109 640 393 429 352  35 599 877 861 836 279   0
 180  28 154 337 844 567 630 384 644 881 767 759 842 896 286   6 454 782
  78 721  74 748 656 763 420 660 324 442 132 118 943 152 717 929 303 334
 314 666 435 456 739 185 357 612 918 363 317 211 794 500 483 653 299 206
 170 201 832 952 301 740 181 587 139  29 968 821  69 388 394  95 272 888
 635 750 217 867 342 498   0  27 775 379]
Prime numbers in array:  [523 109 599 877 337 881 929 739 317 211 653 181 587 139  29 821 379]


**Question 10: Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

**ANS 10]**

In [28]:
#Assuming a month of 30 days
daily_temp = np.random.randint(20,40,30)
print("Daily temperatures for a month: ",daily_temp)
weekly_temp = daily_temp[:28].reshape(4, 7)
weekly_avg = weekly_temp.mean(axis=1)
print("Weekly temperatures: ",weekly_temp)
print("Weekly averages: ",weekly_avg)

Daily temperatures for a month:  [38 28 28 35 29 27 27 23 30 22 21 28 23 29 22 36 35 39 27 24 24 24 30 26
 21 27 27 27 21 23]
Weekly temperatures:  [[38 28 28 35 29 27 27]
 [23 30 22 21 28 23 29]
 [22 36 35 39 27 24 24]
 [24 30 26 21 27 27 27]]
Weekly averages:  [30.28571429 25.14285714 29.57142857 26.        ]
